import type { Category } from "./types";

export const OTHER_CATEGORY_ID = "cat-other";
export const INCOME_CATEGORY_ID = "cat-income";

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: "cat-housing",
    name: "Housing",
    icon: "home",
    colorIndex: 0,
    type: "expense",
    isDefault: true,
    createdAt: new Date(0).toISOString(),
  },
  {
    id: "cat-food",
    name: "Food & Dining",
    icon: "utensils",
    colorIndex: 1,
    type: "expense",
    isDefault: true,
    createdAt: new Date(0).toISOString(),
  },
  {
    id: "cat-transport",
    name: "Transport",
    icon: "car",
    colorIndex: 2,
    type: "expense",
    isDefault: true,
    createdAt: new Date(0).toISOString(),
  },
  {
    id: "cat-shopping",
    name: "Shopping",
    icon: "shopping-bag",
    colorIndex: 3,
    type: "expense",
    isDefault: true,
    createdAt: new Date(0).toISOString(),
  },
  {
    id: "cat-entertainment",
    name: "Entertainment",
    icon: "clapperboard",
    colorIndex: 4,
    type: "expense",
    isDefault: true,
    createdAt: new Date(0).toISOString(),
  },
  {
    id: "cat-utilities",
    name: "Utilities",
    icon: "zap",
    colorIndex: 5,
    type: "expense",
    isDefault: true,
    createdAt: new Date(0).toISOString(),
  },
  {
    id: "cat-health",
    name: "Health",
    icon: "heart-pulse",
    colorIndex: 6,
    type: "expense",
    isDefault: true,
    createdAt: new Date(0).toISOString(),
  },
  {
    id: "cat-subscriptions",
    name: "Subscriptions",
    icon: "repeat",
    colorIndex: 7,
    type: "expense",
    isDefault: true,
    createdAt: new Date(0).toISOString(),
  },
  {
    id: OTHER_CATEGORY_ID,
    name: "Other",
    icon: "more-horizontal",
    colorIndex: 0,
    type: "both",
    isDefault: true,
    createdAt: new Date(0).toISOString(),
  },
  {
    id: INCOME_CATEGORY_ID,
    name: "Income",
    icon: "banknote",
    colorIndex: 0,
    type: "income",
    isDefault: true,
    createdAt: new Date(0).toISOString(),
  },
];
